FROM node:8.9.1

RUN apt-get update -qqy \
  && apt-get -qqy install \
       gnupg wget ca-certificates apt-transport-https \
       fonts-droid ttf-wqy-zenhei ttf-wqy-microhei fonts-arphic-ukai fonts-arphic-uming \
  && rm -rf /var/lib/apt/lists/* /var/cache/apt/*

RUN cd / \
    && npm init -fy \
    && npm install puppeteer@0.13.0

CMD [ "bash" ]
